### PR TITLE
Added "Powered by Netlify" to footer

### PR DESCRIPTION
**Pull request by Ilyesbdlala**
Closes https://github.com/secureCodeBox/documentation/issues/260

Signed-off-by: Ilyes Ben Dlala <ilyes.bendlala@iteratec.com>

### CODE REVIEW

**Comment by Ilyesbdlala** [comment]
> Netlify docs say it has to be a link: https://www.netlify.com/legal/open-source-policy/
> 
>     * Must feature a link to our service on your main page, or all internal pages. You have two options:
>       
>       * We have [premade badges](https://www.netlify.com/press/#badges) for your convenience, or
>       * You may create your own link, which should read “This site is powered by Netlify”, and include a link back to our home page.

Applied the change.

**Comment by J12934** [comment]
I guess Data Protection wise pulling the image directly from netlify.com is fine as we are already hosting the site on netlify?
Or should we move the image to our repo and host it from our domain, just to be sure? @malexmave do you maybe have a option on that?

**Comment by malexmave** [comment]
The "cleaner" version would be to host it ourselves, I guess, since this doesn't trigger a 3rd party request on every page load. Less for the actual difference in privacy in case Netlify turns malicious, and more for the load time / complexity. Or we simply go with the plain text version and avoid the image alltogether.

**Comment by Ilyesbdlala** [comment]
> I guess Data Protection wise pulling the image directly from netlify.com is fine as we are already hosting the site on netlify? Or should we move the image to our repo and host it from our domain, just to be sure? @malexmave do you maybe have a option on that?

As a point of reference, This is also how Docusaurus implements this on their website.
https://github.com/facebook/docusaurus/blob/main/website/docusaurus.config.js#L559-L564

**Pull request merged**
